### ISSUE TITLE
Data disappeared suddenly from Ma cave a vins app

### ISSUE THREAD

**Issue by ogeraud78** [legrandced/Support#1]
Working with filters at some point no more data would be displayed.
Tried to disconnect / reconnect but no change. All the data disappeared and it looks empty.
My email: ogeraud@gmail.com
Thank you

**Comment by legrandced** [comment]
> 

Thank you to have reported your issue. One of your wine data was badly encoded. There wasn't any information about it in the database so I just deleted it from your list. Now, the app should work correctly.

**Comment by ogeraud78** [comment]
Perfect, I checked and everything ok now 😊
Very much appreciate the support 👍

Olivier
